# Site settings
title: Mahbubul Majumder
email: mahbub72@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I intend to share the struggled experiences I had while learning. If this saves time for others, I will be happy. My goal is to write about simple things, since simple tasks appear to be the most complex task in my dictionary. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mamajumder
github_username:  mamajumder

# Build settings
markdown: kramdown
